apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepak-banking
  labels:
    app: deepak-banking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deepak-banking-app
  template:
    metadata:
      labels:
        app: deepak-banking-app
    spec:
      containers:
      - name: deepak-banking-container
        image: deepakdk9938/deepak-banking-app
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: deepak-banking-service
  labels:
    app: deepak-banking-app
spec:
  selector:
    app: deepak-banking-app

  type: NodePort
  ports:
  - nodePort: 31100
    port: 84
    targetPort: 8084
